name: "postprocess"
backend: "python"
max_batch_size: 8

input [
  {
    name: "MODEL_OUTPUT"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

output [
  {
    name: "PERSON_ID"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "IS_PHONE"
    data_type: TYPE_BOOL
    dims: [ 1 ]
  },
  {
    name: "CONFIDENCE"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 1, 4, 8 ]
  max_queue_delay_microseconds: 100
}

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]

version_policy: { all { }}